import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.BorderLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.Color;

public class old_date_box implements ActionListener {
    JPanel panel1 = new JPanel();
    JPanel panel2 = new JPanel();
    JPanel panel3 = new JPanel();
    JPanel panel4 = new JPanel();
    JPanel panel5 = new JPanel();
    JButton bt1 = new JButton();
    JButton bt2 = new JButton();
    JButton bt3 = new JButton();
    JButton bt4 = new JButton();
    JButton bt5 = new JButton();
    JButton bt6 = new JButton();
    JButton bt7 = new JButton();

    JButton bt8 = new JButton();
    JButton bt9 = new JButton();
    JButton bt10 = new JButton();
    JButton bt11 = new JButton();
    JButton bt12 = new JButton();
    JButton bt13 = new JButton();
    JButton bt14 = new JButton();

    JButton bt15 = new JButton();
    JButton bt16 = new JButton();
    JButton bt17 = new JButton();
    JButton bt18 = new JButton();
    JButton bt19 = new JButton();
    JButton bt20 = new JButton();
    JButton bt21 = new JButton();

    JButton bt22 = new JButton();
    JButton bt23 = new JButton();
    JButton bt24 = new JButton();
    JButton bt25 = new JButton();
    JButton bt26 = new JButton();
    JButton bt27 = new JButton();
    JButton bt28 = new JButton();

    JButton bt29 = new JButton();
    JButton bt30 = new JButton();
    JButton bt31 = new JButton();
    JButton bt32 = new JButton();
    JButton bt33 = new JButton();
    JButton bt34 = new JButton();
    JButton bt35 = new JButton();
    String []eStrings={"CT","AS","PR","EX","GG","AS"};
    Dimension dm = new Dimension(100,100);
    String actullyDate[] = new String[35];
        public void paint_Date_button(){
            panel1.removeAll();
            panel2.removeAll();
            panel3.removeAll();
            panel4.removeAll();
            panel5.removeAll();
    
            bt1.removeAll();
            bt2.removeAll();
            bt3.removeAll();
            bt4.removeAll();
            bt5.removeAll();
            bt6.removeAll();
            bt7.removeAll();
    
            bt8.removeAll();
            bt9.removeAll();
            bt10.removeAll();
            bt11.removeAll();
            bt12.removeAll();
            bt13.removeAll();
            bt14.removeAll();
    
            bt15.removeAll();
            bt16.removeAll();
            bt17.removeAll();
            bt18.removeAll();
            bt19.removeAll();
            bt20.removeAll();
            bt21.removeAll();
    
            bt22.removeAll();
            bt23.removeAll();
            bt24.removeAll();
            bt25.removeAll();
            bt26.removeAll();
            bt27.removeAll();
            bt28.removeAll();
    
            bt29.removeAll();
            bt30.removeAll();
            bt31.removeAll();
            bt32.removeAll();
            bt33.removeAll();
            bt34.removeAll();
            bt32.removeAll();
    
    
            bt1.add(new DateLable( actullyDate[0],eStrings).DLPanel);
            //bt1.add(box1.DLPanel);
            bt1.addActionListener(this);
            bt1.setPreferredSize(dm);
            bt1.setBorder(null);
            panel1.add(bt1);
            bt2.add(new DateLable( actullyDate[1],eStrings).DLPanel);
            bt2.addActionListener(this);
            bt2.setPreferredSize(dm);
            bt2.setBorder(null);
            panel1.add(bt2);
            bt3.add(new DateLable( actullyDate[2],eStrings).DLPanel);
            bt3.addActionListener(this);
            bt3.setPreferredSize(dm);
            bt3.setBorder(null);
            panel1.add(bt3);
            bt4.add(new DateLable( actullyDate[3],eStrings).DLPanel);
            bt4.addActionListener(this);
            bt4.setPreferredSize(dm);
            bt4.setBorder(null);
            panel1.add(bt4);
            bt5.add(new DateLable( actullyDate[4],eStrings).DLPanel);
            bt5.addActionListener(this);
            bt5.setPreferredSize(dm);
            bt5.setBorder(null);
            panel1.add(bt5);
            bt6.add(new DateLable( actullyDate[5],eStrings).DLPanel);
            bt6.addActionListener(this);
            bt6.setPreferredSize(dm);
            bt6.setBorder(null);
            panel1.add(bt6);
            bt7.add(new DateLable(actullyDate[6],eStrings).DLPanel);
            bt7.addActionListener(this);
            bt7.setPreferredSize(dm);
            bt7.setBorder(null);
            panel1.add(bt7);
            //panel1.setLayout(new GridLayout(1,7));
            //panel1.setBounds(0, 30, 700, 100);
            bt8.add(new DateLable(actullyDate[7],eStrings).DLPanel);
            bt8.addActionListener(this);
            bt8.setPreferredSize(dm);
            bt8.setBorder(null);
            panel2.add(bt8);
            bt9.add(new DateLable(actullyDate[8],eStrings).DLPanel);
            bt9.addActionListener(this);
            bt9.setPreferredSize(dm);
            bt9.setBorder(null);
            panel2.add(bt9);
            bt10.add(new DateLable(actullyDate[9],eStrings).DLPanel);
            bt10.addActionListener(this);
            bt10.setPreferredSize(dm);
            bt10.setBorder(null);
            panel2.add(bt10);
            bt11.add(new DateLable(actullyDate[10],eStrings).DLPanel);
            bt11.addActionListener(this);
            bt11.setPreferredSize(dm);
            bt11.setBorder(null);
            panel2.add(bt11);
            bt12.add(new DateLable(actullyDate[11],eStrings).DLPanel);
            bt12.addActionListener(this);
            bt12.setPreferredSize(dm);
            bt12.setBorder(null);
            panel2.add(bt12);
            bt13.add(new DateLable(actullyDate[12],eStrings).DLPanel);
            bt13.addActionListener(this);
            bt13.setPreferredSize(dm);
            bt13.setBorder(null);
            panel2.add(bt13);
            bt14.add(new DateLable(actullyDate[13],eStrings).DLPanel);
            bt14.addActionListener(this);
            bt14.setPreferredSize(dm);
            bt14.setBorder(null);
            panel2.add(bt14);
    
            bt15.add(new DateLable(actullyDate[14],eStrings).DLPanel);
            bt15.addActionListener(this);
            bt15.setPreferredSize(dm);
            bt15.setBorder(null);
            panel3.add(bt15);
            bt16.add(new DateLable(actullyDate[15],eStrings).DLPanel);
            bt16.addActionListener(this);
            bt16.setPreferredSize(dm);
            bt16.setBorder(null);
            panel3.add(bt16);
            bt17.add(new DateLable(actullyDate[16],eStrings).DLPanel);
            bt17.addActionListener(this);
            bt17.setPreferredSize(dm);
            bt17.setBorder(null);
            panel3.add(bt17);
            bt18.add(new DateLable(actullyDate[17],eStrings).DLPanel);
            bt18.addActionListener(this);
            bt18.setPreferredSize(dm);
            bt18.setBorder(null);
            panel3.add(bt18);
            bt19.add(new DateLable(actullyDate[18],eStrings).DLPanel);
            bt19.addActionListener(this);
            bt19.setPreferredSize(dm);
            bt19.setBorder(null);
            panel3.add(bt19);
            bt20.add(new DateLable(actullyDate[19],eStrings).DLPanel);
            bt20.addActionListener(this);
            bt20.setPreferredSize(dm);
            bt20.setBorder(null);
            panel3.add(bt20);
            bt21.add(new DateLable(actullyDate[20],eStrings).DLPanel);
            bt21.addActionListener(this);
            bt21.setPreferredSize(dm);
            bt21.setBorder(null);
            panel3.add(bt21);
    
            bt22.add(new DateLable(actullyDate[21],eStrings).DLPanel);
            bt22.addActionListener(this);
            bt22.setPreferredSize(dm);
            bt22.setBorder(null);
            panel4.add(bt22);
            bt23.add(new DateLable(actullyDate[22],eStrings).DLPanel);
            bt23.addActionListener(this);
            bt23.setPreferredSize(dm);
            bt23.setBorder(null);
            panel4.add(bt23);
            bt24.add(new DateLable(actullyDate[23],eStrings).DLPanel);
            bt24.addActionListener(this);
            bt24.setPreferredSize(dm);
            bt24.setBorder(null);
            panel4.add(bt24);
            bt25.add(new DateLable(actullyDate[24],eStrings).DLPanel);
            bt25.addActionListener(this);
            bt25.setPreferredSize(dm);
            bt25.setBorder(null);
            panel4.add(bt25);
            bt26.add(new DateLable(actullyDate[25],eStrings).DLPanel);
            bt26.addActionListener(this);
            bt26.setPreferredSize(dm);
            bt26.setBorder(null);
            panel4.add(bt26);
            bt27.add(new DateLable(actullyDate[26],eStrings).DLPanel);
            bt27.addActionListener(this);
            bt27.setPreferredSize(dm);
            bt27.setBorder(null);
            panel4.add(bt27);
            bt28.add(new DateLable(actullyDate[27],eStrings).DLPanel);
            bt28.addActionListener(this);
            bt28.setPreferredSize(dm);
            bt28.setBorder(null);
            panel4.add(bt28);
    
            bt29.add(new DateLable(actullyDate[28],eStrings).DLPanel);
            bt29.addActionListener(this);
            bt29.setPreferredSize(dm);
            bt29.setBorder(null);
            panel5.add(bt29);
            bt30.add(new DateLable(actullyDate[29],eStrings).DLPanel);
            bt30.addActionListener(this);
            bt30.setPreferredSize(dm);
            bt30.setBorder(null);
            panel5.add(bt30);
            bt31.add(new DateLable(actullyDate[30],eStrings).DLPanel);
            bt31.addActionListener(this);
            bt31.setPreferredSize(dm);
            bt31.setBorder(null);
            panel5.add(bt31);
            bt32.add(new DateLable(actullyDate[31],eStrings).DLPanel);
            bt32.addActionListener(this);
            bt32.setPreferredSize(dm);
            bt32.setBorder(null);
            panel5.add(bt32);
            bt33.add(new DateLable(actullyDate[32],eStrings).DLPanel);
            bt33.addActionListener(this);
            bt33.setPreferredSize(dm);
            bt33.setBorder(null);
            panel5.add(bt33);
            bt34.add(new DateLable(actullyDate[33],eStrings).DLPanel);
            bt34.addActionListener(this);
            bt34.setPreferredSize(dm);
            bt34.setBorder(null);
            panel5.add(bt34);
            bt35.add(new DateLable(actullyDate[34],eStrings).DLPanel);
            bt35.addActionListener(this);
            bt35.setPreferredSize(dm);
            bt35.setBorder(null);
            panel5.add(bt35);
    
        }
        @Override
        public void actionPerformed(ActionEvent e) {
            // TODO Auto-generated method stub
            
        }
    }

